plugins {
    id 'java'
    id 'org.gretty' version '4.1.5'
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly group: 'jakarta.servlet',
            name: 'jakarta.servlet-api',
            version: '6.1.0'

    compileOnly 'org.projectlombok:lombok:1.18.34'

    annotationProcessor 'org.projectlombok:lombok:1.18.34'

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.5'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.13.5'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.13.5'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
}

gretty {
    servletContainer = 'jetty11'
    contextPath = '/'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}


