plugins {
    id 'java'
    id 'war'
    id 'org.gretty' version '4.1.5'
}

repositories {
    mavenCentral()
}

dependencies {
    providedCompile 'jakarta.servlet:jakarta.servlet-api:6.1.0'
}

gretty {
    servletContainer = 'jetty11'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

war {
    archiveFileName = 'icd0011.war'
    from 'src/main/webapp'
}

