plugins {
    id 'java'
    id 'org.gretty' version '4.1.5'
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly group: 'jakarta.servlet',
            name: 'jakarta.servlet-api',
            version: '6.1.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
}

gretty {
    servletContainer = 'jetty11'
    contextPath = '/'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}


