DROP SCHEMA PUBLIC CASCADE;

DROP TABLE IF EXISTS order_rows;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS AUTHORITIES;
DROP SEQUENCE IF EXISTS seq1;
DROP INDEX IF EXISTS ix_auth_username;
-- DROP SEQUENCE IF EXISTS seq2;

-- CREATE SEQUENCE seq2 AS INTEGER START WITH 1 INCREMENT BY 1;

CREATE TABLE USERS (
   username VARCHAR(255) NOT NULL PRIMARY KEY,
   password VARCHAR(255) NOT NULL,
   enabled BOOLEAN NOT NULL,
   first_name VARCHAR(255) NOT NULL
);

CREATE TABLE AUTHORITIES (
     username VARCHAR(50) NOT NULL,
     authority VARCHAR(50) NOT NULL,
     FOREIGN KEY (username) REFERENCES USERS ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_auth_username ON AUTHORITIES (username, authority);

CREATE SEQUENCE seq1 AS INTEGER START WITH 1 INCREMENT BY 1;

CREATE TABLE orders (
    id BIGINT NOT NULL PRIMARY KEY,
    order_number VARCHAR(255)
);

CREATE TABLE order_rows (
    item_name VARCHAR(255),
    price INT,
    quantity INT,
    orders_id BIGINT,
    FOREIGN KEY (orders_id)
        REFERENCES orders(id) ON DELETE CASCADE
);